import fs from 'fs';
import path from 'path';

export interface CursorRulesContext {
  accountInfo: any;
  auditDate: string;
  keyMetrics: any;
  criticalIssues: string[];
  recommendations: any[];
  activeCampaigns: any[];
  accountHealthScore?: number;
}

export function generateCursorRules(context: CursorRulesContext): string {
  const formatCurrency = (micros: number, currency: string) => {
    return `${currency} ${(micros / 1000000).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  const spend = context.keyMetrics?.cost_micros || 0;
  const clicks = context.keyMetrics?.clicks || 0;
  const conversions = context.keyMetrics?.conversions || 0;
  const ctr = context.keyMetrics?.ctr || 0;

  return `# Google Ads Account Context - Auto-Generated

Last Updated: ${new Date(context.auditDate).toLocaleString()}

## Account Overview
- **Account:** ${context.accountInfo.descriptive_name || 'Unknown'}
- **Customer ID:** ${context.accountInfo.id || 'Unknown'}
- **Currency:** ${context.accountInfo.currency_code || 'USD'}
- **Status:** ${context.accountInfo.status || 'Unknown'}
${context.accountHealthScore ? `- **Health Score:** ${context.accountHealthScore}/10` : ''}

## Performance Summary (Last 30 Days)
- **Total Spend:** ${formatCurrency(spend, context.accountInfo.currency_code || 'USD')}
- **Total Clicks:** ${clicks.toLocaleString()}
- **Click-Through Rate:** ${(ctr * 100).toFixed(2)}%
- **Conversions:** ${conversions}
${conversions > 0 ? `- **Cost per Conversion:** ${formatCurrency(spend / conversions, context.accountInfo.currency_code || 'USD')}` : ''}

## Active Campaigns
${context.activeCampaigns.length > 0
  ? context.activeCampaigns.slice(0, 5).map((c, idx) =>
      `${idx + 1}. **${c.campaign?.name || 'Unknown'}** (${c.campaign?.advertising_channel_type || 'Unknown'})`
    ).join('\n')
  : '- No active campaigns found'
}
${context.activeCampaigns.length > 5 ? `\n... and ${context.activeCampaigns.length - 5} more` : ''}

## 🔴 Critical Issues
${context.criticalIssues.length > 0
  ? context.criticalIssues.map((issue, idx) => `${idx + 1}. ${issue}`).join('\n')
  : '- No critical issues identified'
}

## 💡 Top Recommendations
${context.recommendations.length > 0
  ? context.recommendations.slice(0, 5).map((r, idx) =>
      `${idx + 1}. **[${r.priority?.toUpperCase()}]** ${r.action}`
    ).join('\n')
  : '- No recommendations available'
}

## Quick Commands
\`\`\`bash
# List all campaigns
npm run dev -- campaigns ${context.accountInfo.id}

# Re-run audit
npm run dev -- audit ${context.accountInfo.id}

# Generate PDF report
npm run dev -- audit ${context.accountInfo.id} --output audit-${new Date().toISOString().split('T')[0]}.pdf
\`\`\`

## Next Actions
1. Review critical issues in detail
2. Prioritize high-impact recommendations
3. Update tracking implementation
4. Schedule weekly performance review
5. Re-run audit after changes

---
*Auto-generated by Google Ads Wizard CLI*
*Following PostHog Wizard patterns: deterministic analysis, temperature 0*
`;
}

export function saveCursorRules(context: CursorRulesContext, dir = '.') {
  const cursorDir = path.join(dir, '.cursor');

  if (!fs.existsSync(cursorDir)) {
    fs.mkdirSync(cursorDir, { recursive: true });
  }

  const content = generateCursorRules(context);
  const rulesPath = path.join(cursorDir, 'rules');

  fs.writeFileSync(rulesPath, content);

  return rulesPath;
}
